version: "3.7"

x-buildargs: &build_args
  GIT_COMMIT: ${GIT_COMMIT:-'git-commit'}
  BUILD_VERSION: ${BUILD_VERSION:-'semver'}

services:
  ui:
    image: ${CR_BASE:-ghcr.io/implex1v}/pnpmusicapp-ui:${BUILD_VERSION:-latest}
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
    - api
    environment:
      APP_PUBLIC_API_URL: http://localhost:8080
    build:
      context: ./ui/
      args:
        <<: *build_args

  api:
    image: ${CR_BASE:-ghcr.io/implex1v}/pnpmusicapp-api:${BUILD_VERSION:-latest}
    restart: unless-stopped
    ports:
      - 8080:8080
    build: 
      context: ./api/
      args:
        <<: *build_args
    depends_on:
    - "mongo"
    networks:
    - "db"
    environment:
      APP_MONGODB_HOST: mongo
      APP_MONGODB_PORT: "27017"
      APP_MONGODB_USERNAME: pnpmusicapp
      APP_MONGODB_PASSWORD: password
      APP_MONGODB_DATABASE: pnpmusicapp

  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - 27017:27017
    networks:
      - db
    environment:
      MONGO_INITDB_ROOT_USERNAME: pnpmusicapp
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: pnpmusicapp

networks:
  db:

volumes:
  songs:
