version: "3.7"

x-buildargs: &build_args
  GIT_COMMIT: ${GIT_COMMIT:-'git-commit'}
  BUILD_VERSION: ${GITVERSION_SEMVER:-'semver'}

services:
  ui:
    image: ${CR_BASE:-local}/ui:${GITVERSION_SEMVER:-latest}
    restart: unless-stopped
    depends_on:
    - api
    build:
      context: ./ui/
      args:
        <<: *build_args

  # this builds or runs api/Dockerfile
  api:
    # path of the builded docker image
    image: ${CR_BASE:-local}/api:${GITVERSION_SEMVER:-latest}
    restart: unless-stopped
    build: 
      # path, where the Dockerfile is
      context: ./api/
      # gives args for commit...
      args:
        <<: *build_args
    depends_on:
    - db
    networks:
      - "db"
  
  db:
    image: ${CR_BASE:-local}/db:${GITVERSION_SEMVER:-latest}
    restart: unless-stopped
    networks:
      - "db"

  mongo:
    image: mongo:6
    restart: always
    ports:
      - 27017:27017
    networks:
      - db
    environment:
      MONGO_INITDB_ROOT_USERNAME: pnpmusicapp
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: pnpmusicapp

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - db
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: pnpmusicapp
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://pnpmusicapp:password@mongo:27017/

networks:
  db: