apiVersion: v2
name: api
description: Helm chart for the API of PnPMusicApp
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: mongodb # https://artifacthub.io/packages/helm/bitnami/mongodb
    version: ~13.3.0
    repository: https://charts.bitnami.com/bitnami
