replicaCount: 1
baseDomain: cloud.example.com

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecret: pull-secret
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "public"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"

resources:
   requests:
     cpu: 50m
     memory: 128Mi
   limits:
     cpu: 100m
     memory: 256Mi

nodeSelector: {}
tolerations: []
affinity: {}

mongodb:
  # app specific
  username: pnpmusicapp
  host: api-mongodb
  port: 27017
  password: unset
  database: pnpmusicapp

  architecture: standalone

  persistence:
    enabled: true
    size: 8Gi

  auth:
    rootPassword: unset
    usernames:
      - pnpmusicapp
    passwords: []
    databases:
      - pnpmusicapp

  metrics:
    # -- Enable [Prometheus metrics for MongoDb](https://artifacthub.io/packages/helm/bitnami/mongodb#metrics-parameters)
    enabled: true
    serviceMonitor:
      # -- If the prometheus operator is installed in your cluster, set to true to create a Service Monitor Entry
      enabled: true

