spring:
  data:
    mongodb:
      host: ${APP_MONGODB_HOST:localhost}
      port: ${APP_MONGODB_PORT:27017}
      username: ${APP_MONGODB_USERNAME:pnpmusicapp}
      password: ${APP_MONGODB_PASSWORD:password}
      database: ${APP_MONGODB_DATABASE:pnpmusicapp}
      authentication-database: admin
      auto-index-creation: true

app:
  file:
    location: /opt/pnpmusicapp/songs/

logging:
  level:
    reactor:
      netty:
        http:
          # client: DEBUG # enable netty request logging
    org:
      springframework:
        data:
          mongodb:
            core:
              # ReactiveMongoTemplate: DEBUG # enable printing of mongo queries