name: _build

on:
  workflow_call:
    inputs:
      component:
        description: The component to build
        type: string
        required: true
      version:
        description: The current version
        type: string
        required: true
    secrets:
      cr:
        description: The container registry to use (default is GitHub)
        required: true
      cr_token:
        description: The container registry token
        required: true
      cr_user:
        description: The registry user
        required: true
    outputs:
      version:
        value: ${{ jobs.builds.outputs.version }}

defaults:
  run:
    shell: bash

env:
  COMPONENT: ${{ inputs.component }}

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      CR_BASE: ${{ secrets.cr }}
      GITVERSION_SEMVER: ${{ needs.version.outputs.semver }}
      GIT_COMMIT: ${{ github.sha }}
      BUILD_VERSION: ${{ inputs.version }}
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      #------ 
      - uses: actions/checkout@v3
      # https://github.com/docker/login-action
      - name: docker login
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.cr }}
          username: ${{ secrets.cr_user }}
          password: ${{ secrets.cr_token }}
      - name: Build container image
        run: |
          docker-compose build ${COMPONENT}
          docker-compose push ${COMPONENT}
      - name: Retag to latest and push image
        run: |
          docker tag ${CR_BASE}/pnpmusicapp-${COMPONENT}:${BUILD_VERSION} ${CR_BASE}/pnpmusicapp-${COMPONENT}:latest
          docker push ${CR_BASE}/pnpmusicapp-${COMPONENT}:latest
      - id: version
        run: echo "version=${BUILD_VERSION}" >> $GITHUB_OUTPUT